In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('iris')

In [6]:
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [7]:
df.tail(10)

     sepal_length  sepal_width  petal_length  petal_width    species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [8]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [11]:
df.shape

(150, 5)

In [13]:
df['petal_length']

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [17]:
df.loc[0,['sepal_length','petal_width']]

sepal_length    5.1
petal_width     0.2
Name: 0, dtype: object

In [18]:
df.iloc[0,0:-1]

sepal_length    5.1
sepal_width     3.5
petal_length    1.4
petal_width     0.2
Name: 0, dtype: object

In [22]:
df.isnull().sum().sum()

np.int64(0)

In [24]:
df.dropna(inplace=True)

In [30]:
df.rename(columns={'sepal_length':'sepal'},inplace=True)

In [31]:
df.columns

Index(['sepal', 'sepal_width', 'petal_length', 'petal_width', 'species'], dtype='object')

In [33]:
df.sort_values('sepal',ascending=False)

     sepal  sepal_width  petal_length  petal_width    species
131    7.9          3.8           6.4          2.0  virginica
122    7.7          2.8           6.7          2.0  virginica
118    7.7          2.6           6.9          2.3  virginica
117    7.7          3.8           6.7          2.2  virginica
135    7.7          3.0           6.1          2.3  virginica
..     ...          ...           ...          ...        ...
41     4.5          2.3           1.3          0.3     setosa
42     4.4          3.2           1.3          0.2     setosa
8      4.4          2.9           1.4          0.2     setosa
38     4.4          3.0           1.3          0.2     setosa
13     4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [34]:
df.value_counts('species')

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [ ]:
df.to_csv('iris')