In [1]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [2]:
data = pd.DataFrame(
    {
        'color':['red','blue','green','green','red','blue']
    }
)

In [3]:
data

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [6]:
encoder = OneHotEncoder()
encoded_df = encoder.fit_transform(data).toarray()

In [7]:
encoded_df = pd.DataFrame(encoded_df,columns=encoder.get_feature_names_out())

In [8]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [13]:
import seaborn as sns 
df = sns.load_dataset('tips')

In [14]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [19]:
encoder = OneHotEncoder()
encodeed = encoder.fit_transform(df[['sex','smoker','day','time']]).toarray()

In [20]:
encoded_df = pd.DataFrame(encodeed,columns=encoder.get_feature_names_out())
encoded_df

     sex_Female  sex_Male  smoker_No  ...  day_Thur  time_Dinner  time_Lunch
0           1.0       0.0        1.0  ...       0.0          1.0         0.0
1           0.0       1.0        1.0  ...       0.0          1.0         0.0
2           0.0       1.0        1.0  ...       0.0          1.0         0.0
3           0.0       1.0        1.0  ...       0.0          1.0         0.0
4           1.0       0.0        1.0  ...       0.0          1.0         0.0
..          ...       ...        ...  ...       ...          ...         ...
239         0.0       1.0        1.0  ...       0.0          1.0         0.0
240         1.0       0.0        0.0  ...       0.0          1.0         0.0
241         0.0       1.0        0.0  ...       0.0          1.0         0.0
242         0.0       1.0        1.0  ...       0.0          1.0         0.0
243         1.0       0.0        1.0  ...       1.0          1.0         0.0

[244 rows x 10 columns]

In [23]:
full_df = pd.concat([df,encoded_df],axis=1)

In [24]:
full_df

     total_bill   tip     sex  ... day_Thur time_Dinner time_Lunch
0         16.99  1.01  Female  ...      0.0         1.0        0.0
1         10.34  1.66    Male  ...      0.0         1.0        0.0
2         21.01  3.50    Male  ...      0.0         1.0        0.0
3         23.68  3.31    Male  ...      0.0         1.0        0.0
4         24.59  3.61  Female  ...      0.0         1.0        0.0
..          ...   ...     ...  ...      ...         ...        ...
239       29.03  5.92    Male  ...      0.0         1.0        0.0
240       27.18  2.00  Female  ...      0.0         1.0        0.0
241       22.67  2.00    Male  ...      0.0         1.0        0.0
242       17.82  1.75    Male  ...      0.0         1.0        0.0
243       18.78  3.00  Female  ...      1.0         1.0        0.0

[244 rows x 17 columns]